### ISSUE TITLE
Relative path seems to be based on the node_modules directory and not the cwd

### ISSUE THREAD

**Issue by EtienneDx** [ferdikoomen/openapi-typescript-codegen#2048]
**Describe the bug**
When running the command with a relative path, I'm getting a path error. Seems weird that it happens and haven't been mentioned yet but I don't think it's linked to my usage. I tried using npx and running through a package.json script.

```bash
> openapi --input ../back-end/openapi/main_service.json --output ./src/openapis --exportSchemas true

{
  stack: 'JSONParserError: Error opening file "D:\\Documents\\Projets\\fullstack-app-experimentation\\front-ent\\node_modules\\@apidevtools\\json-schema-ref-parser\\back-end\\openapi\\main_service.json" \n' +
    "ENOENT: no such file or directory, open 'D:\\Documents\\Projets\\fullstack-app-experimentation\\front-ent\\node_modules\\@apidevtools\\json-schema-ref-parser\\back-end\\openapi\\main_service.json'\n" +
    '    at Object.<anonymous> (D:\\Documents\\Projets\\fullstack-app-experimentation\\front-ent\\node_modules\\@apidevtools\\json-schema-ref-parser\\dist\\lib\\resolvers\\file.js:72:23)\n' +    
    '    at Generator.throw (<anonymous>)\n' +
    '    at rejected (D:\\Documents\\Projets\\fullstack-app-experimentation\\front-ent\\node_modules\\@apidevtools\\json-schema-ref-parser\\dist\\lib\\resolvers\\file.js:29:65)',
  name: 'ResolverError',
  message: 'Error opening file "D:\\Documents\\Projets\\fullstack-app-experimentation\\front-ent\\node_modules\\@apidevtools\\json-schema-ref-parser\\back-end\\openapi\\main_service.json" \n' +  
    "ENOENT: no such file or directory, open 'D:\\Documents\\Projets\\fullstack-app-experimentation\\front-ent\\node_modules\\@apidevtools\\json-schema-ref-parser\\back-end\\openapi\\main_service.json'",
  path: null,
  toJSON: [Function: toJSON],
  ioErrorCode: 'ENOENT',
  footprint: 'null+D:\\Documents\\Projets\\fullstack-app-experimentation\\front-ent\\node_modules\\@apidevtools\\json-schema-ref-parser\\back-end\\openapi\\main_service.json+ERESOLVER+Error openi    "ENOENT: no such file or directory, open 'D:\\Documents\\Projets\\fullstack-app-experimentation\\front-ent\\node_modules\\@apidevtools\\json-schema-ref-parser\\back-end\\openapi\\main_service.json'",
  toString: [Function: toString]
}
```

OS: Windows 10

**Comment by mrlubos** [comment]
Duplicate of https://github.com/ferdikoomen/openapi-typescript-codegen/issues/1970

**Comment by EtienneDx** [comment]
My bad

**Comment by mrlubos** [comment]
@EtienneDx we've got a fix for this in [our fork](https://github.com/nicolas-chaulet/openapi-typescript-codegen), could you give it a try and see if it works for you?
