### ISSUE TITLE
Error running openapi when OAS "info" missing

### ISSUE THREAD

**Issue by crizo23** [ferdikoomen/openapi-typescript-codegen#430]
This is more of a user error, but perhaps the error reported could be better. When my OAS spec is missing the `info` object, I get:
```
TypeError: Cannot read property 'version' of undefined
    at ae (/Users/user/.nvm/versions/node/v12.18.4/lib/node_modules/openapi-typescript-codegen/dist/index.js:1:31340)
    at Object.exports.generate (/Users/user/.nvm/versions/node/v12.18.4/lib/node_modules/openapi-typescript-codegen/dist/index.js:1:96527)
```

With some OAS codegen libraries one of the first things done is to validate the spec (using [oas-validator](https://www.npmjs.com/package/oas-validator), for example) and return an "invalid spec" error if it's invalid. Would this be possible?

**Comment by ferdikoomen** [comment]
@crizo23 i added it to the roadmap, im working on a @next version that has a better error messages
