### ISSUE TITLE
TypeError: e.trim is not a function when generating Discourse client

### ISSUE THREAD

**Issue by LucianBuzzo** [ferdikoomen/openapi-typescript-codegen#739]
When trying to Generate code using the Discourse API spec I get the following error:
```
(node:13295) UnhandledPromiseRejectionWarning: TypeError: e.trim is not a function
    at /home/lucian/projects/discourse-sdk/node_modules/openapi-typescript-codegen/dist/index.js:1:17416
    at J (/home/lucian/projects/discourse-sdk/node_modules/openapi-typescript-codegen/dist/index.js:1:17803)
    at K (/home/lucian/projects/discourse-sdk/node_modules/openapi-typescript-codegen/dist/index.js:1:24639)
    at Z (/home/lucian/projects/discourse-sdk/node_modules/openapi-typescript-codegen/dist/index.js:1:19223)
    at K (/home/lucian/projects/discourse-sdk/node_modules/openapi-typescript-codegen/dist/index.js:1:24476)
    at /home/lucian/projects/discourse-sdk/node_modules/openapi-typescript-codegen/dist/index.js:1:32027
    at ue (/home/lucian/projects/discourse-sdk/node_modules/openapi-typescript-codegen/dist/index.js:1:32721)
    at /home/lucian/projects/discourse-sdk/node_modules/openapi-typescript-codegen/dist/index.js:1:34245
    at pe (/home/lucian/projects/discourse-sdk/node_modules/openapi-typescript-codegen/dist/index.js:1:34424)
    at Object.exports.generate (/home/lucian/projects/discourse-sdk/node_modules/openapi-typescript-codegen/dist/index.js:1:141018)
```

This is the script I'm using to generate the client:
```js
const OpenAPI = require('openapi-typescript-codegen');

const SPEC_URL = 'https://docs.discourse.org/openapi.json'

OpenAPI.generate({
    input: SPEC_URL,
    output: './dist',
    write: true
});
```

This is with `v0.9.3` of this module.

**Comment by ferdikoomen** [comment]
@LucianBuzzo it seems they use the type as an array value `type: ["string", "null"]` that is allowed via the JSON Schema draft (december 2020, page 17), but was not supported. I added support for this. Will publish a new version (0.10.0) soon too NPM.

**Comment by leye0** [comment]
Any update on supporting type as an array value? It would allow supporting nullables in general.
