### ISSUE TITLE
nodejs 12, SyntaxError: Unexpected token '.'

### ISSUE THREAD

**Issue by overmike** [ferdikoomen/openapi-typescript-codegen#996]
**Describe the bug**
Thanks for your package. Just to make everyone aware the tool does not support nodejs v12, and I am able to use it with nodejs 14/16. If there is no intention to support nodejs 12, please ignore this.

```
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/someone/.nvm/versions/node/v12.22.10/lib/node_modules/openapi-typescript-codegen/bin/index.js:29:17)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
```

**Comment by eLvErDe** [comment]
For the record I did a manual bisect and 0.12.5 is the last version that works with NodeJS 12.

**Comment by ferdikoomen** [comment]
@overmike @eLvErDe I pushed a change to the main branch that should have NodeJS 12 support. Also the local development build itself should work again with NodeJS 12 (although some features might not work like e2e tests and eslint). I will push a new version of the generator today.
